Repository spring-projects/spring-amqp, pull requests merged in 2023-01, with the labels that each got.

#1552 Fix Testcontainer Tests With No Docker Running
  build.gradle
  spring-rabbit-junit/src/main/java/org/springframework/amqp/rabbit/junit/AbstractTestContainerTests.java
Labels: type: task

#1555 Upgrade Spring, Micrometer, Reactor Versions
  build.gradle
Labels: type: dependency-upgrade

#1558 Fix typos in documentation
  src/reference/asciidoc/amqp.adoc
  src/reference/asciidoc/appendix.adoc
  src/reference/asciidoc/stream.adoc
  src/reference/asciidoc/testing.adoc
Labels: type: documentation
