Repository spring-projects/spring-amqp, pull requests merged in 2023-09, with the labels that each got.

#2520 Output of `asciidoctorPdf` can be pulled from cache when run on machines with different checkout directories
  build.gradle
Labels: type: task, in: build

#2521 Main to 3.1; Upgrade Dependency Versions
  build.gradle
  gradle.properties
  spring-rabbit/src/test/java/org/springframework/amqp/rabbit/AsyncRabbitTemplateTests.java
  spring-rabbit/src/test/java/org/springframework/amqp/rabbit/annotation/EnableRabbitIntegrationTests.java
  spring-rabbit/src/test/java/org/springframework/amqp/rabbit/listener/MethodRabbitListenerEndpointTests.java
  spring-rabbit/src/test/resources/org/springframework/amqp/rabbit/annotation/annotation-driven-full-config.xml
  spring-rabbit/src/test/resources/org/springframework/amqp/rabbit/annotation/annotation-driven-full-configurable-config.xml
  spring-rabbit/src/test/resources/org/springframework/amqp/rabbit/annotation/annotation-driven-sample-config.xml
  spring-rabbit/src/test/resources/org/springframework/amqp/rabbit/config/ConnectionFactoryParserTests-context.xml
  spring-rabbit/src/test/resources/org/springframework/amqp/rabbit/config/ExchangeParserTests-context.xml
  spring-rabbit/src/test/resources/org/springframework/amqp/rabbit/config/QueueParserPlaceholderTests-context.xml
  spring-rabbit/src/test/resources/org/springframework/amqp/rabbit/config/QueueParserTests-context.xml
  spring-rabbit/src/test/resources/org/springframework/amqp/rabbit/config/TemplateParserTests-context.xml
Labels: type: dependency-upgrade

#2525 Upgrade Spring, Data, Retry, Reactor, Micrometer, Jackson Versions
  build.gradle
Labels: type: dependency-upgrade

#2526 Upgrade Spring, Data, Retry, Reactor, Micrometer
  build.gradle
Labels: type: dependency-upgrade

#2530 GH-2456: (Re) Support Spring Framework 5.2
  spring-rabbit/src/main/java/org/springframework/amqp/rabbit/annotation/RabbitListenerAnnotationBeanPostProcessor.java
Labels: type: enhancement
