Repository spring-projects/spring-amqp, pull requests merged in 2024-10, with the labels that each got.

#2839 Add RabbitTemplate getBeforePublishPostProcessors method
  spring-rabbit/src/main/java/org/springframework/amqp/rabbit/core/RabbitTemplate.java
Labels: type: enhancement

#2854 Improve condition for `convertLongStringIfNecessary` from `DefaultMessagePropertiesConverter`
  spring-rabbit/src/main/java/org/springframework/amqp/rabbit/support/DefaultMessagePropertiesConverter.java
Labels: type: refactoring

#2857 Fix typo in sending-messages.adoc
  src/reference/antora/modules/ROOT/pages/amqp/sending-messages.adoc
Labels: type: documentation
