Repository spring-projects/spring-amqp, pull requests merged in 2025-02, with the labels that each got.

#2952 Fix README on publishing to local Maven
  README.md
Labels: type: documentation

#2961 Add convenient getter for stream name
  spring-rabbit-stream/src/main/java/org/springframework/rabbit/stream/listener/StreamListenerContainer.java
Labels: type: enhancement, for: backport-to-3.2.x

#2958 Fix typo in `CONTRIBUTING` and `README`
  CONTRIBUTING.adoc
  README.md
Labels: type: documentation

#2977 Improve `build.gradle` for building antora
  build.gradle
  src/reference/antora/antora-playbook.yml
  src/reference/antora/antora.yml
  src/reference/antora/modules/ROOT/pages/amqp/broker-configuration.adoc
  src/reference/antora/modules/ROOT/pages/amqp/connections.adoc
  src/reference/antora/modules/ROOT/pages/amqp/listener-queues.adoc
  src/reference/antora/modules/ROOT/pages/amqp/receiving-messages/async-annotation-driven/enable.adoc
  src/reference/antora/modules/ROOT/pages/amqp/receiving-messages/micrometer.adoc
  src/reference/antora/modules/ROOT/pages/amqp/request-reply.adoc
  src/reference/antora/modules/ROOT/pages/amqp/sending-messages.adoc
  src/reference/antora/modules/ROOT/pages/amqp/transactions.adoc
  src/reference/antora/modules/ROOT/pages/sample-apps.adoc
Labels: in: build
